"""
bot.py — Main Bot Execution Loop
Schedules and orchestrates the entire trading process.
"""

import time
import schedule
from datetime import datetime

import config
import notifier
import exchange
import strategy
from risk import RiskManager
from logger import get_logger

log = get_logger("bot")
risk = RiskManager()


def tick(binance):
    """Main execution logic, run periodically by scheduler."""
    log.info(f"--- Tick: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ---")

    try:
        # 1. Fetch current balances
        usdt_balance = exchange.get_balance_usdt(binance)
        log.debug(f"Available balance: ${usdt_balance:.2f} USDT")

        # 2. Check kill switch
        if risk.check_kill_switch(usdt_balance):
            log.warning("Kill switch is active. Skipping tick.")
            return

        # 3. Fetch OHLCV data & Current Price
        df = exchange.fetch_ohlcv(binance)
        current_price = df.iloc[-1]['close'] # Get latest closing price or use get_current_price

        # 4. Check exit conditions for existing positions
        if risk.has_position:
            exit_reason = risk.check_exit_conditions(current_price)
            if exit_reason:
                # Close position
                qty_to_sell = risk.position.quantity
                order = exchange.execute_sell(binance, qty_to_sell)
                if order:
                    pnl_usdt, pnl_pct = risk.close_position(current_price)
                    notifier.send_sell(
                        price=current_price,
                        qty=qty_to_sell,
                        usdt_received=order.get('cost', qty_to_sell * current_price),
                        pnl=pnl_usdt,
                        pnl_pct=pnl_pct,
                        reason=exit_reason.replace("_", " ").upper()
                    )
            else:
                log.info(f"Holding open position (Current Price: ${current_price:.2f})")
            return # Don't analyze for new entries if holding a position

        # 5. Analyze Market for Entry Signals
        res = strategy.analyze(df)

        if res.signal == strategy.Signal.BUY:
            log.info(f"BUY Signal detected! Reason: {res.reason}")
            trade_amount = risk.calculate_trade_size(usdt_balance)
            
            if trade_amount >= 10.0:
                order = exchange.execute_buy(binance, trade_amount)
                if order:
                    # Calculate actual received quantity and spent amount
                    # In DRY_RUN, we use simulated values from the order dict
                    qty = order.get('amount', trade_amount / res.price)
                    spent = order.get('cost', trade_amount)
                    
                    risk.open_position(entry_price=res.price, quantity=qty, usdt_spent=spent)
                    notifier.send_buy(
                        price=res.price,
                        qty=qty,
                        usdt_spent=spent,
                        ema_short=res.ema_short,
                        ema_long=res.ema_long,
                        rsi=res.rsi
                    )
            else:
                log.warning(f"Trade amount (${trade_amount:.2f}) is below minimum requirement ($10.0). Skipping entry.")

        elif res.signal == strategy.Signal.SELL:
             # Strategy says SELL, but we handle exits via Risk Manager (Stop Loss / Take Profit)
             # or if we wanted to close early based on signal:
             log.debug("SELL signal generated by strategy, but no open position to close.")
             notifier.send_signal_skip("SELL", res.rsi, "No open position")

        else:
            log.debug(f"Status: HOLD. {res.reason}")

    except Exception as e:
        log.exception(f"Error during tick: {e}")
        notifier.send_error(str(e))


def send_daily_report():
    """Send daily summary of trading activity."""
    try:
        stats = risk.status()
        # Note: In a real scenario, you'd fetch the actual total balance.
        # Here we approximate for simplicity or fetch it.
        notifier.send_daily_summary(
            total_trades=stats['daily_trades'],
            wins=stats['daily_wins'],
            losses=stats['daily_losses'],
            total_pnl=stats['daily_pnl'],
            balance=0.0 # Placeholder, should fetch real balance if needed for report
        )
    except Exception as e:
         log.error(f"Error sending daily report: {e}")


def main():
    log.info("Starting Trading Bot...")
    config.validate()
    
    config_summary = config.summary()
    log.info(config_summary)
    notifier.send_startup(config_summary)

    try:
        binance_client = exchange.connect()
    except Exception as e:
        log.critical(f"Failed to connect to exchange: {e}")
        notifier.send_error(f"Failed to connect to exchange: {e}")
        return

    # Scheduling
    # Run tick every hour at minute 0 (e.g., 10:00, 11:00)
    schedule.every().hour.at(":00").do(tick, binance=binance_client)
    
    # Daily summary at 23:55
    schedule.every().day.at("23:55").do(send_daily_report)

    log.info("Scheduler started. Waiting for next interval...")
    
    # Optional: Run immediately on startup for testing/first entry
    # tick(binance_client)

    while True:
        try:
            schedule.run_pending()
            time.sleep(10)
        except KeyboardInterrupt:
            log.info("Bot stopped manually by user.")
            break
        except Exception as e:
            log.error(f"Error in scheduler loop: {e}")
            time.sleep(60)

if __name__ == "__main__":
    main()
